# Generated by Django 4.0 on 2022-01-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_studentlist_teachers_studentlist_mainteacher_and_more'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.ManyToManyField(blank=True, related_name='class_name', to='student.StudentList', verbose_name='Sınıs Adı')),
                ('lessons', models.ManyToManyField(blank=True, related_name='lessonName', to='lessons.Lesson', verbose_name='Dersler')),
            ],
        ),
    ]
