# Generated by Django 4.0 on 2022-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_studentlist_teachers_studentlist_mainteacher_and_more'),
        ('lessons', '0002_lessonclasslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonclasslist',
            name='className',
            field=models.ManyToManyField(to='student.StudentList'),
        ),
        migrations.AlterField(
            model_name='lessonclasslist',
            name='lessons',
            field=models.ManyToManyField(to='lessons.Lesson'),
        ),
    ]
