# Generated by Django 4.0 on 2022-01-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_studentlist_teachers_studentlist_mainteacher_and_more'),
        ('lessons', '0003_lesson_code_alter_lessonclasslist_classname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonclasslist',
            name='className',
        ),
        migrations.AddField(
            model_name='lessonclasslist',
            name='className',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_lesson', to='student.studentlist'),
            preserve_default=False,
        ),
    ]
