# Generated by Django 4.0 on 2022-01-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lessonclasslist_classname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonclasslist',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lessonclasslist',
            name='lessons',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_lesson', to='lessons.lesson'),
            preserve_default=False,
        ),
    ]
