# Generated by Django 4.0 on 2022-01-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211215_1623'),
        ('student', '0013_remove_studentlist_teachers_studentlist_mainteacher_and_more'),
        ('lessons', '0005_remove_lessonclasslist_lessons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonclasslist',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lessonclasslist',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_lesson', to='lessons.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonclasslist',
            name='teacher',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_profil', to='home.profil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonclasslist',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_classname', to='student.studentlist'),
        ),
    ]
