# Generated by Django 4.0 on 2022-01-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_lessonperiods_lesscount_lessonperiods_periods_and_more'),
        ('lessons', '0006_remove_lessonclasslist_lessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonplan_lessonclasslist', to='lessons.lessonclasslist')),
                ('lessonPeriods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonplan_LessonPeriods', to='attendance.lessonperiods')),
            ],
        ),
    ]
