# Generated by Django 3.2.5 on 2021-12-02 18:54

import apps.student.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0015_alter_profil_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, max_length=20, null=True)),
                ('TC', models.CharField(blank=True, max_length=11, null=True, validators=[apps.student.models.validateEven])),
                ('phone', models.CharField(blank=True, default='0', max_length=17, null=True, validators=[apps.student.models.validatePhone])),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='https://picsum.photos/200/300', null=True, upload_to='images')),
                ('health', models.TextField(blank=True, null=True)),
                ('HESCode', models.CharField(blank=True, max_length=12, null=True, validators=[apps.student.models.validateHesCode])),
                ('birtdate', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihiniz')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Kız', 'Kız'), ('Erkek', 'Erkek'), ('Diger', 'Diğer')], max_length=10, null=True)),
                ('middleSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.middleschool')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('relation', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('phone', models.IntegerField()),
                ('adsreds', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('job', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('student', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
