# Generated by Django 4.0 on 2022-02-01 06:55

import apps.student.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=20)),
                ('lastName', models.CharField(blank=True, max_length=20, null=True)),
                ('TC', models.CharField(max_length=11, unique=True, validators=[apps.student.models.validateEven])),
                ('phone', models.CharField(blank=True, default='0', max_length=17, null=True, validators=[apps.student.models.validatePhone])),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='images/person.png', null=True, upload_to=apps.student.models.upload_location)),
                ('health', models.TextField(blank=True, null=True)),
                ('HESCode', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.student.models.validateHesCode])),
                ('birtdate', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihiniz')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Kız', 'Kız'), ('Erkek', 'Erkek'), ('Diger', 'Diğer')], max_length=10, null=True)),
                ('middleSchool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.middleschool')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.session')),
            ],
            options={
                'ordering': ('firstName',),
            },
        ),
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_arrangement', models.CharField(default=' / / / / / / / / / / / / / / / / / / / / / / / ', max_length=10000)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('mainteacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='home.profil', verbose_name='Sınıf Öğretmeni')),
                ('periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.period')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session')),
                ('students', models.ManyToManyField(blank=True, to='student.Student')),
            ],
            options={
                'ordering': ('className', 'session', 'periods'),
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('relation', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('phone', models.IntegerField()),
                ('adsreds', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('job', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('student', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
