# Generated by Django 3.2.5 on 2021-12-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='student.Student'),
        ),
    ]
