# Generated by Django 3.2.5 on 2021-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentlist_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='studentss', to='student.Student'),
        ),
    ]
