# Generated by Django 3.2.5 on 2021-12-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_profil_image'),
        ('student', '0004_alter_studentlist_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentlist',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teacher', to='home.Profil', verbose_name='Sınıf Öğretmeni'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student', to='student.Student'),
        ),
    ]
