# Generated by Django 3.2.5 on 2021-12-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20211206_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='images/person.png', null=True, upload_to='images'),
        ),
    ]
