# Generated by Django 3.2.5 on 2021-12-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('firstName',)},
        ),
    ]
