# Generated by Django 3.2.5 on 2021-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
