# Generated by Django 3.2.5 on 2021-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
