# Generated by Django 3.2.5 on 2021-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentlist_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='images/person.png', null=True, upload_to='images/ogrenciler/'),
        ),
    ]
