# Generated by Django 3.2.5 on 2021-12-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211212_1820'),
        ('student', '0010_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='periods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.period'),
            preserve_default=False,
        ),
    ]
