# Generated by Django 4.0 on 2022-01-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentlist_periods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlist',
            options={'ordering': ('className', 'session', 'periods')},
        ),
    ]
