# Generated by Django 4.0 on 2022-01-14 06:13

import apps.student.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211215_1623'),
        ('student', '0012_alter_studentlist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='teachers',
        ),
        migrations.AddField(
            model_name='studentlist',
            name='mainteacher',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='home.profil', verbose_name='Sınıf Öğretmeni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='images/person.png', null=True, upload_to=apps.student.models.upload_location),
        ),
    ]
