# Generated by Django 4.0 on 2022-01-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211215_1623'),
        ('student', '0013_remove_studentlist_teachers_studentlist_mainteacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middleSchool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.middleschool'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
    ]
