# Generated by Django 4.0 on 2022-01-28 19:04

import apps.student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studentlist_seating_arrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='HESCode',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.student.models.validateHesCode]),
        ),
        migrations.AlterField(
            model_name='student',
            name='TC',
            field=models.CharField(default=1, max_length=11, unique=True, validators=[apps.student.models.validateEven]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
