# Generated by Django 4.0 on 2022-01-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211215_1623'),
        ('student', '0016_alter_student_hescode_alter_student_tc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='mainteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='home.profil', verbose_name='Sınıf Öğretmeni'),
        ),
    ]
