# Generated by Django 3.2.5 on 2021-11-26 10:36

import apps.home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='2021-2022', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(max_length=11, unique=True, validators=[apps.home.models.validateEven])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/')),
                ('phone', models.CharField(blank=True, default='05', max_length=17, null=True, validators=[apps.home.models.validatePhone])),
                ('adress', models.TextField(max_length=100)),
                ('isWorking', models.BooleanField(default=True)),
                ('HESCode', models.CharField(max_length=12, unique=True, validators=[apps.home.models.validateHesCode])),
                ('birthdate', models.DateField(verbose_name='Doğum Tarihiniz')),
                ('gender', models.CharField(choices=[('KIZ', 'Kız'), ('erkek', 'Erkek'), ('diger', 'Diğer')], max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jobstable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
