# Generated by Django 3.2.5 on 2021-11-25 20:26

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnketListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='cevaplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DersIzlemeSinavlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disVerileri', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Donem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yillar', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GorevTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.TextField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanicilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
                ('soyAd', models.CharField(max_length=20)),
                ('TC', models.CharField(max_length=11, unique=True, validators=[apps.home.models.validateEven])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/')),
                ('telefonNo', models.CharField(blank=True, default='0', max_length=17, null=True, validators=[apps.home.models.validatePhone])),
                ('adres', models.TextField(max_length=75)),
                ('calismaDurumu', models.BooleanField(default=True)),
                ('yetki', models.BooleanField(default=False)),
                ('hes_Kodu', models.CharField(max_length=12, unique=True, validators=[apps.home.models.validateHesCode])),
                ('dogumTarihi', models.DateField(verbose_name='Doğum Tarihiniz')),
                ('email', models.EmailField(max_length=254)),
                ('cinsiyet', models.CharField(choices=[('KIZ', 'Kız'), ('erkek', 'Erkek'), ('diger', 'Diğer')], max_length=10)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.gorevtablosu')),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(default='', max_length=20)),
                ('soyAd', models.CharField(max_length=20)),
                ('TC', models.CharField(max_length=11, unique=True, validators=[apps.home.models.validateEven])),
                ('telefonNo', models.CharField(blank=True, default='0', max_length=17, null=True, validators=[apps.home.models.validatePhone])),
                ('adres', models.TextField()),
                ('okulDevamDurumu', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('saglikDurumu', models.TextField(null=True)),
                ('hes_Kodu', models.CharField(max_length=12, unique=True, validators=[apps.home.models.validateHesCode])),
                ('dogumTarihi', models.DateField(verbose_name='Doğum Tarihiniz')),
                ('ogrenciNo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cinsiyet', models.CharField(choices=[('KIZ', 'Kız'), ('erkek', 'Erkek'), ('diger', 'Diğer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrtaOkulListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okulAdi', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SoruListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorular', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubeListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subeAdi', models.CharField(default='A', max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VeliListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(default='', max_length=20)),
                ('soyAd', models.CharField(max_length=20)),
                ('yakinlikDurumu', models.CharField(max_length=20)),
                ('telefonNo', models.IntegerField()),
                ('adres', models.TextField()),
                ('meslek', models.CharField(max_length=20)),
                ('ogrenci', models.ManyToManyField(to='home.OgrenciListesi')),
            ],
        ),
        migrations.CreateModel(
            name='SinifListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinifNo', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('donem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.donem')),
                ('ogrrenciListesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ogrencilistesi')),
                ('subeAdi', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.subelistesi')),
            ],
        ),
        migrations.CreateModel(
            name='RaporSinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anket_sonucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.anketlistesi')),
                ('dis', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.dersizlemesinavlari')),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.siniflistesi')),
            ],
        ),
        migrations.CreateModel(
            name='RaporOgrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roporTuru', models.CharField(choices=[('dıs', 'DİS'), ('anket', 'Anket'), ('not', 'Not Raporu')], max_length=10)),
                ('anket_sonucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.anketlistesi')),
                ('cevaplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cevaplar')),
                ('degerlendiren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kullanicilar')),
                ('donem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.donem')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ogrencilistesi')),
            ],
        ),
        migrations.AddField(
            model_name='ogrencilistesi',
            name='geldigiOkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ortaokullistesi'),
        ),
        migrations.AddField(
            model_name='ogrencilistesi',
            name='kayitYili',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.donem'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.question')),
            ],
        ),
        migrations.AddField(
            model_name='anketlistesi',
            name='donem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.donem'),
        ),
        migrations.AddField(
            model_name='anketlistesi',
            name='sorular',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.sorulistesi'),
        ),
    ]
