# Generated by Django 4.0 on 2022-02-01 06:55

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='1.Dönem', max_length=10, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='2021-2022', max_length=10, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.period')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[apps.home.models.validateEven])),
                ('image', models.ImageField(blank=True, default='images/person.png', null=True, upload_to=apps.home.models.upload_location)),
                ('phone', models.CharField(blank=True, default='05', max_length=17, null=True, validators=[apps.home.models.validatePhone])),
                ('adress', models.TextField(blank=True, max_length=100, null=True)),
                ('isWorking', models.BooleanField(blank=True, default=True, null=True)),
                ('HESCode', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.home.models.validateHesCode])),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihiniz')),
                ('gender', models.CharField(blank=True, choices=[('Kız', 'Kız'), ('Erkek', 'Erkek'), ('Diger', 'Diğer')], max_length=10, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.jobstable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user')),
            ],
        ),
    ]
