# Generated by Django 3.2.5 on 2021-11-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='image',
            field=models.ImageField(blank=True, default='https://picsum.photos/200/300', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('dıs', 'DİS'), ('not', 'Not Raporu'), ('anket', 'Anket')], max_length=10),
        ),
    ]
