# Generated by Django 3.2.5 on 2021-11-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211126_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='image',
            field=models.ImageField(blank=True, default='https://picsum.photos/200/300', null=True, upload_to='images/%Y/'),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('dıs', 'DİS'), ('anket', 'Anket'), ('not', 'Not Raporu')], max_length=10),
        ),
    ]
