# Generated by Django 3.2.5 on 2021-11-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211126_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/'),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('dıs', 'DİS'), ('not', 'Not Raporu')], max_length=10),
        ),
    ]
