# Generated by Django 3.2.5 on 2021-11-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('home', '0004_auto_20211128_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilDetail',
        ),
    ]
