# Generated by Django 3.2.5 on 2021-11-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211126_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='soyAd',
            field=models.CharField(max_length=20, verbose_name='Soyad'),
        ),
    ]
