# Generated by Django 3.2.5 on 2021-11-28 18:47

import apps.home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_delete_profildetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[apps.home.models.validateEven])),
                ('image', models.ImageField(blank=True, default='images/person.png', null=True, upload_to='images/%Y/')),
                ('phone', models.CharField(blank=True, default='05', max_length=17, null=True, validators=[apps.home.models.validatePhone])),
                ('adress', models.TextField(blank=True, max_length=100, null=True)),
                ('isWorking', models.BooleanField(blank=True, default=True, null=True)),
                ('HESCode', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.home.models.validateHesCode])),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihiniz')),
                ('gender', models.CharField(blank=True, choices=[('Kız', 'Kız'), ('Erkek', 'Erkek'), ('Diger', 'Diğer')], max_length=10, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.jobstable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfilDetay',
        ),
    ]
