# Generated by Django 3.2.5 on 2021-11-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_kullanicilar_soyad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('not', 'Not Raporu'), ('dıs', 'DİS')], max_length=10),
        ),
    ]
