# Generated by Django 3.2.5 on 2021-11-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_raporogrenci_roporturu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('dıs', 'DİS'), ('not', 'Not Raporu'), ('anket', 'Anket')], max_length=10),
        ),
    ]
