# Generated by Django 3.2.5 on 2021-11-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(blank=True, default='images/person.png', null=True, upload_to='images/ogretmen/'),
        ),
    ]
