# Generated by Django 3.2.5 on 2021-11-30 10:46

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_profil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(blank=True, default='images/person.png', null=True, upload_to=apps.home.models.logo_dir_path),
        ),
    ]
