# Generated by Django 3.2.5 on 2021-12-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_profil_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='1.Dönem', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.period')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.session')),
            ],
        ),
    ]
