# Generated by Django 3.2.5 on 2021-12-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_period_sessionperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionperiod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.period'),
        ),
        migrations.AlterField(
            model_name='sessionperiod',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
    ]
