# Generated by Django 3.2.5 on 2021-12-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211212_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
