# Generated by Django 3.2.5 on 2021-11-25 12:15

import apps.polls.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/%Y/', verbose_name=models.CharField(max_length=11, unique=True, validators=[apps.polls.views.validateEven])),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('not', 'Not Raporu'), ('dıs', 'DİS')], max_length=10),
        ),
    ]
