# Generated by Django 3.2.5 on 2021-11-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20211125_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('not', 'Not Raporu'), ('dıs', 'DİS'), ('anket', 'Anket')], max_length=10),
        ),
    ]
