# Generated by Django 3.2.5 on 2021-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_raporogrenci_roporturu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('dıs', 'DİS'), ('anket', 'Anket'), ('not', 'Not Raporu')], max_length=10),
        ),
    ]
