# Generated by Django 3.2.5 on 2021-12-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesPeriod', models.CharField(default='9:30-10:10', max_length=15, unique=True)),
            ],
        ),
    ]
