# Generated by Django 4.0 on 2022-02-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('day', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPeriods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lessCount', models.IntegerField(default='1')),
                ('lessName', models.CharField(default='1.Ders', max_length=15, verbose_name='Ders No')),
                ('lesPeriod', models.CharField(default='09:30-10:10', max_length=15)),
            ],
        ),
    ]
