# Generated by Django 3.2.5 on 2021-12-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentlist_periods'),
        ('home', '0018_auto_20211215_1623'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True)),
                ('lesPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.lessonperiods')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
