# Generated by Django 4.0 on 2022-02-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('home', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonperiods',
            name='periods',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.period'),
        ),
        migrations.AddField(
            model_name='lessonperiods',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='lesPeriod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.lessonperiods'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='periods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.period'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
