# Generated by Django 3.2.5 on 2021-12-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentlist_periods'),
        ('attendance', '0002_dailyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentlist'),
        ),
    ]
