# Generated by Django 3.2.5 on 2021-12-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentlist_periods'),
        ('attendance', '0004_alter_dailyattendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='student',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='studentlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studentlist'),
            preserve_default=False,
        ),
    ]
