# Generated by Django 3.2.5 on 2021-12-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentlist_periods'),
        ('attendance', '0005_auto_20211217_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='studentlist',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
    ]
