# Generated by Django 3.2.5 on 2021-12-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211215_1623'),
        ('attendance', '0006_auto_20211217_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='periods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
            preserve_default=False,
        ),
    ]
