# Generated by Django 4.0 on 2022-01-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211215_1623'),
        ('attendance', '0008_lessonperiods_lessname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonperiods',
            name='lessCount',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='lessonperiods',
            name='periods',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.period'),
        ),
        migrations.AddField(
            model_name='lessonperiods',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
        migrations.AlterField(
            model_name='lessonperiods',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lessonperiods',
            name='lesPeriod',
            field=models.CharField(default='09:30-10:10', max_length=15),
        ),
    ]
