# Generated by Django 3.2.6 on 2021-11-21 04:59

from django.db import migrations, models
import django.db.models.deletion
import polls.views


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnketListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='cevaplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DersIzlemeSinavlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disVerileri', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Donem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yillar', models.TextField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GorevTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.TextField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanicilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
                ('soyAd', models.CharField(max_length=20)),
                ('TC', models.IntegerField(unique=True, validators=[polls.views.validate_even])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('telefonNo', models.IntegerField(validators=[polls.views.validate_evenz])),
                ('adres', models.CharField(max_length=75)),
                ('calismaDurumu', models.BooleanField()),
                ('yetki', models.BooleanField()),
                ('hes_Kodu', models.CharField(max_length=12, unique=True)),
                ('dogumTarihi', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('cinsiyet', models.CharField(choices=[('KIZ', 'Kız'), ('erkek', 'Erkek'), ('diger', 'Diğer')], max_length=10)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gorevtablosu')),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(default='', editable=False, max_length=20)),
                ('soyAd', models.CharField(max_length=20)),
                ('TC', models.IntegerField(validators=[polls.views.validate_even])),
                ('telefonNo', models.IntegerField(unique=True, validators=[polls.views.validate_evenz])),
                ('adres', models.TextField()),
                ('okulDevamDurumu', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('saglikDurumu', models.TextField()),
                ('hesKodu', models.CharField(max_length=12, unique=True)),
                ('dogumTarihi', models.CharField(max_length=12)),
                ('ogrenciNo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cinsiyet', models.CharField(choices=[('KIZ', 'Kız'), ('erkek', 'Erkek'), ('diger', 'Diğer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrtaOkulListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okulAdi', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoruListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorular', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubeListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subeAdi', models.CharField(default='A', max_length=1, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='VeliListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(default='', max_length=20)),
                ('soyAd', models.CharField(max_length=20)),
                ('yakinlikDurumu', models.CharField(max_length=20)),
                ('telefonNo', models.IntegerField()),
                ('adres', models.TextField()),
                ('meslek', models.CharField(max_length=20)),
                ('ogrenci', models.ManyToManyField(to='polls.OgrenciListesi')),
            ],
        ),
        migrations.CreateModel(
            name='SinifListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinifNo', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('donem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.donem')),
                ('ogrrenciListesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ogrencilistesi')),
                ('subeAdi', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.subelistesi')),
            ],
        ),
        migrations.CreateModel(
            name='RaporSinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anket_sonucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.anketlistesi')),
                ('dis', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.dersizlemesinavlari')),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.siniflistesi')),
            ],
        ),
        migrations.CreateModel(
            name='RaporOgrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roporTuru', models.CharField(choices=[('dıs', 'DİS'), ('not', 'Not Raporu'), ('anket', 'Anket')], max_length=10)),
                ('anket_sonucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.anketlistesi')),
                ('cevaplar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.cevaplar')),
                ('degerlendiren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.kullanicilar')),
                ('donem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.donem')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ogrencilistesi')),
            ],
        ),
        migrations.AddField(
            model_name='ogrencilistesi',
            name='geldigiOkul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.ortaokullistesi'),
        ),
        migrations.AddField(
            model_name='ogrencilistesi',
            name='kayitYili',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.donem'),
        ),
        migrations.AddField(
            model_name='anketlistesi',
            name='donem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.donem'),
        ),
        migrations.AddField(
            model_name='anketlistesi',
            name='sorular',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.sorulistesi'),
        ),
    ]
