# Generated by Django 3.2.5 on 2021-11-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnketListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DersIzlemeSinavlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_verileri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yıllar', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GorevTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kullanicilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('TC', models.IntegerField(max_length=11, unique=True)),
                ('phoneNumber', models.IntegerField(max_length=10)),
                ('adress', models.TextField()),
                ('Çalışma_Durumu', models.BooleanField()),
                ('yetki', models.BooleanField()),
                ('gorev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.gorevtablosu')),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('TC', models.IntegerField(max_length=11, unique=True)),
                ('adress', models.TextField()),
                ('OkulDevam', models.BooleanField()),
                ('veli', models.CharField(max_length=20)),
                ('KayıtYılı', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.donem')),
            ],
        ),
        migrations.CreateModel(
            name='OrtaOkulListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoruListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorular', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubeListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VeliListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('Yakınlık_Durumu', models.TextField()),
                ('phoneNumber', models.IntegerField(max_length=10)),
                ('adress', models.TextField()),
                ('brans', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.gorevtablosu')),
                ('ogrenci', models.ManyToManyField(to='polls.OgrenciListesi')),
            ],
        ),
        migrations.CreateModel(
            name='SinifListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sınıf_no', models.IntegerField(unique=True)),
                ('donem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.donem')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ogrencilistesi')),
                ('sube_adi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.subelistesi')),
            ],
        ),
        migrations.CreateModel(
            name='RaporSinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anket_sonucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.anketlistesi')),
                ('dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.dersizlemesinavlari')),
                ('sınıf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.siniflistesi')),
            ],
        ),
        migrations.CreateModel(
            name='RaporOgrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevaplar', models.IntegerField()),
                ('anket_sonucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.anketlistesi')),
                ('degerlendiren', models.ManyToManyField(to='polls.Kullanicilar')),
                ('dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.dersizlemesinavlari')),
                ('donem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.donem')),
            ],
        ),
        migrations.AddField(
            model_name='ogrencilistesi',
            name='geldigiOkul',
            field=models.ManyToManyField(to='polls.OrtaOkulListesi'),
        ),
        migrations.AddField(
            model_name='anketlistesi',
            name='sorular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sorulistesi'),
        ),
    ]
