# Generated by Django 3.2.5 on 2021-11-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211118_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donem',
            name='yıllar',
            field=models.TextField(),
        ),
    ]
