# Generated by Django 3.2.6 on 2021-11-21 05:46

from django.db import migrations, models
import polls.views


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211121_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='telefonNo',
            field=models.CharField(blank=True, default='0', max_length=17, null=True, validators=[polls.views.validatePhone]),
        ),
    ]
