# Generated by Django 3.2.5 on 2021-11-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_donem_yıllar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donem',
            name='yıllar',
            field=models.TextField(max_length=15),
        ),
    ]
