# Generated by Django 3.2.6 on 2021-11-22 05:00

from django.db import migrations, models
import polls.views


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_kullanicilar_telefonno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name=models.IntegerField(max_length=17, unique=True, validators=[polls.views.validate_even])),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('dıs', 'DİS'), ('not', 'Not Raporu')], max_length=10),
        ),
    ]
