# Generated by Django 3.2.5 on 2021-11-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211118_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrencilistesi',
            name='veli',
        ),
        migrations.AlterField(
            model_name='subelistesi',
            name='subeAdi',
            field=models.CharField(default='A', max_length=1, unique=True),
        ),
    ]
