# Generated by Django 3.2.5 on 2021-11-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211118_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrencilistesi',
            name='geldigiOkul',
        ),
        migrations.AddField(
            model_name='ogrencilistesi',
            name='geldigiOkul',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.ortaokullistesi'),
            preserve_default=False,
        ),
    ]
