# Generated by Django 3.2.5 on 2021-11-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20211118_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velilistesi',
            name='brans',
        ),
        migrations.AddField(
            model_name='velilistesi',
            name='meslek',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siniflistesi',
            name='sinifNo',
            field=models.IntegerField(),
        ),
    ]
