# Generated by Django 3.2.6 on 2021-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_raporogrenci_roporturu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogrencilistesi',
            old_name='hesKodu',
            new_name='hes_Kodu',
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('dıs', 'DİS'), ('not', 'Not Raporu'), ('anket', 'Anket')], max_length=10),
        ),
    ]
