# Generated by Django 3.2.5 on 2021-11-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_velilistesi_yakinlikdurumu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanicilar',
            name='gorev',
        ),
        migrations.AddField(
            model_name='kullanicilar',
            name='gorev',
            field=models.ManyToManyField(blank=True, to='polls.GorevTablosu'),
        ),
    ]
