# Generated by Django 3.2.9 on 2021-11-23 21:06

import apps.polls.views
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donem',
            name='yillar',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='TC',
            field=models.CharField(max_length=11, unique=True, validators=[apps.polls.views.validateEven]),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='gorev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='polls.gorevtablosu'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name=models.CharField(max_length=11, unique=True, validators=[apps.polls.views.validateEven])),
        ),
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='TC',
            field=models.CharField(max_length=11, unique=True, validators=[apps.polls.views.validateEven]),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('dıs', 'DİS'), ('anket', 'Anket'), ('not', 'Not Raporu')], max_length=10),
        ),
    ]
