# Generated by Django 3.2.9 on 2021-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211124_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('dıs', 'DİS'), ('not', 'Not Raporu'), ('anket', 'Anket')], max_length=10),
        ),
    ]
