# Generated by Django 3.2.6 on 2021-11-21 05:25

from django.db import migrations, models
import polls.views


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211121_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='adres',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='dogumTarihi',
            field=models.DateField(verbose_name='Doğum Tarihiniz'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='telefonNo',
            field=models.CharField(blank=True, default='0505-', max_length=17, null=True, validators=[polls.views.validatePhone]),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('dıs', 'DİS'), ('not', 'Not Raporu')], max_length=10),
        ),
    ]
