# Generated by Django 3.2.6 on 2021-11-21 05:42

from django.db import migrations, models
import polls.views


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211121_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='TC',
            field=models.IntegerField(max_length=17, unique=True, validators=[polls.views.validate_even]),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='hes_Kodu',
            field=models.CharField(max_length=12, unique=True, validators=[polls.views.validateHesCode]),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('not', 'Not Raporu'), ('dıs', 'DİS')], max_length=10),
        ),
    ]
