# Generated by Django 3.2.6 on 2021-11-22 05:26

from django.db import migrations, models
import polls.views


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211122_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='TC',
            field=models.IntegerField(unique=True, validators=[polls.views.validate_even]),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='calismaDurumu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name=models.IntegerField(unique=True, validators=[polls.views.validate_even])),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='yetki',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='TC',
            field=models.IntegerField(unique=True, validators=[polls.views.validate_even]),
        ),
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='ad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='dogumTarihi',
            field=models.DateField(verbose_name='Doğum Tarihiniz'),
        ),
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='hesKodu',
            field=models.CharField(max_length=12, unique=True, validators=[polls.views.validateHesCode]),
        ),
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='okulDevamDurumu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='saglikDurumu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='telefonNo',
            field=models.CharField(blank=True, default='0', max_length=17, null=True, validators=[polls.views.validatePhone]),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('not', 'Not Raporu'), ('dıs', 'DİS')], max_length=10),
        ),
    ]
