# Generated by Django 3.2.6 on 2021-11-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20211122_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrencilistesi',
            name='kayitYili',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.donem'),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='cevaplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cevaplar'),
        ),
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('not', 'Not Raporu'), ('dıs', 'DİS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='siniflistesi',
            name='subeAdi',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.subelistesi'),
        ),
    ]
