# Generated by Django 3.2.6 on 2021-11-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20211122_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('not', 'Not Raporu'), ('dıs', 'DİS'), ('anket', 'Anket')], max_length=10),
        ),
    ]
