# Generated by Django 4.0 on 2022-02-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='9', max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A', max_length=1, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classes.classnames')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classlevels')),
            ],
        ),
    ]
