# Generated by Django 3.2.5 on 2021-12-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevels',
            name='level',
            field=models.CharField(default='9', max_length=2, unique=True),
        ),
    ]
