# Generated by Django 4.0 on 2022-02-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ('level', 'className')},
        ),
    ]
