# Generated by Django 3.2.5 on 2021-12-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20211205_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentList',
        ),
    ]
