# Generated by Django 3.2.5 on 2021-12-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_delete_studentlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classnames',
            options={'ordering': ('name',)},
        ),
    ]
